import {Store} from './store';

export const Adorama: Store = {
  currency: '$',
  labels: {
    captcha: {
      container: 'body',
      text: ['please verify you are a human'],
    },
    inStock: {
      container: '.buy-section.purchase',
      text: ['add to cart'],
    },
    maxPrice: {
      container: '.your-price',
      euroFormat: false,
    },
  },
  links: [
    {
      brand: 'test:brand',
      model: 'test:model',
      series: 'test:series',
      url: 'https://www.adorama.com/ev08gp43067k.html',
    },
    {
      name: 'Asus GeForce RTX 3060 TUF Gaming OC',
      brand: 'asus',
      model: 'tuf',
      series: '3060',
      url: 'https://www.adorama.com/as90yv0gc0m0.html',
    },
    {
      name: 'MSI GeForce RTX 3060 Gaming X',
      brand: 'msi',
      model: 'gaming x',
      series: '3060',
      url: 'https://www.adorama.com/msig3060gx12.html',
    },
    {
      name: 'EVGA GeForce RTX 3060 Ti XC Gaming',
      brand: 'evga',
      model: 'xc gaming',
      series: '3060ti',
      url: 'https://www.adorama.com/ev8gp53663.html',
    },
    {
      name: 'EVGA GeForce RTX 3060 Ti FTW3 Ultra Gaming',
      brand: 'evga',
      model: 'ftw3',
      series: '3060ti',
      url: 'https://www.adorama.com/ev8gp53667.html',
    },
    {
      name: 'MSI GeForce RTX 3060 Ti Gaming X Trio',
      brand: 'msi',
      model: 'gaming x',
      series: '3060ti',
      url: 'https://www.adorama.com/msig306tgxt.html',
    },
    {
      name: 'MSI GeForce RTX 3070 Gaming X Trio',
      brand: 'msi',
      model: 'gaming x',
      series: '3070',
      url: 'https://www.adorama.com/msig3070gxt.html',
    },
    {
      name: 'MSI GeForce RTX 3070 SUPRIM X',
      brand: 'msi',
      model: 'suprim',
      series: '3070',
      url: 'https://www.adorama.com/msig3070sx8.html',
    },
    {
      name: 'PNY GeForce RTX 3070 Dual Fan',
      brand: 'pny',
      model: 'dual fan',
      series: '3070',
      url: 'https://www.adorama.com/png30708dfmb.html',
    },
    {
      name: 'EVGA GeForce RTX 3070 XC3 Ultra',
      brand: 'evga',
      model: 'xc3',
      series: '3070',
      url: 'https://www.adorama.com/ev08gp53755k.html',
    },
    {
      name: 'EVGA GeForce RTX 3070 XC3 Black Gaming',
      brand: 'evga',
      model: 'xc3',
      series: '3070',
      url: 'https://www.adorama.com/ev08gp53751k.html',
    },
    {
      name: 'PNY GeForce RTX 3070 XLR8 Gaming',
      brand: 'pny',
      model: 'xlr8 gaming',
      series: '3070',
      url: 'https://www.adorama.com/png30708tfxb.html',
    },
    {
      brand: 'pny',
      model: 'xlr8 revel',
      series: '3080',
      url: 'https://www.adorama.com/pnv301tfxmpb.html',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: '3080',
      url: 'https://www.adorama.com/msig380gxt1.html',
    },
    {
      brand: 'evga',
      model: 'ftw3 ultra',
      series: '3080',
      url: 'https://www.adorama.com/ev10g53897kr.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3080',
      url: 'https://www.adorama.com/ev10g53885kr.html',
    },
    {
      brand: 'evga',
      model: 'ftw3',
      series: '3080',
      url: 'https://www.adorama.com/ev10g53895kr.html',
    },
    {
      brand: 'evga',
      model: 'xc3',
      series: '3080',
      url: 'https://www.adorama.com/ev10g53883kr.html',
    },
    {
      brand: 'evga',
      model: 'xc3 black',
      series: '3080',
      url: 'https://www.adorama.com/ev10g53881kr.html',
    },
    {
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '3080',
      url: 'https://www.adorama.com/msig38v3x10c.html',
    },
    {
      brand: 'pny',
      model: 'xlr8 revel',
      series: '3080',
      url: 'https://www.adorama.com/png30801tfxb.html',
    },
    {
      name: 'Asus GeForce RTX 3080 ROG STRIX OC',
      brand: 'asus',
      model: 'strix oc',
      series: '3080',
      url: 'https://www.adorama.com/asrx3080o10g.html',
    },
    {
      brand: 'asus',
      model: 'tuf oc',
      series: '3080',
      url: 'https://www.adorama.com/astr3080o10g.html',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '3080',
      url: 'https://www.adorama.com/astrx308010g.html',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: '3090',
      url: 'https://www.adorama.com/msig390gxt24.html',
    },
    {
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '3090',
      url: 'https://www.adorama.com/msig39v3x24c.html',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '3090',
      url: 'https://www.adorama.com/asrtx309024g.html',
    },
    {
      brand: 'asus',
      model: 'tuf oc',
      series: '3090',
      url: 'https://www.adorama.com/ast3090o24g.html',
    },
    {
      brand: 'asus',
      model: 'strix oc',
      series: '3090',
      url: 'https://www.adorama.com/asrx3090o24g.html',
    },
  ],
  name: 'adorama',
};
