import {Store} from './store';

export const Intex: Store = {
  currency: '$',
  labels: {
    inStock: {
      container: '#form-action-addToCart',
      text: ['add to cart'],
    },
    maxPrice: {
      container: '.price.price--withoutTax',
      euroFormat: false,
    },
    outOfStock: {
      container: '.productView-product-price-availability > .availability > .stock',
      text: ['not available'],
    },
    productTitle: '.productView-title',
    productImage: '.productView-thumbnail-link > img',
    loginUrl: 'https://intexcorp.com/login.php',
  },
  links: [
    {
      brand: 'test:brand',
      model: 'test:model',
      series: 'test:series',
      url: 'https://intexcorp.com/products/above-ground-pools/easy-set/8ft-x-24in-easy-set-pool-set/',
    },
    {
        brand: 'intex',
        model: 'intex',
        series: 'intex',
        cartUrl: 'https://intexcorp.com/cart.php?action=add&product_id=262',
        url: 'https://intexcorp.com/products/above-ground-pools/krystal-clear-filtration-sanitation/cartridge-filter-pumps/330-gph-krystal-clear-cartridge-filter-pump-110-120v-with-gfci/',
    }, 
    {
        brand: 'intex',
        model: 'intex',
        series: 'intex',
        cartUrl: 'https://intexcorp.com/cart.php?action=add&product_id=219',
        url: 'https://intexcorp.com/products/above-ground-pools/krystal-clear-filtration-sanitation/cartridge-filter-pumps/530-gph-krystal-clear-cartridge-filter-pump-110-120v-with-gfci/',
    },    
    {
        brand: 'intex',
        model: 'intex',
        series: 'intex',
        cartUrl: 'https://intexcorp.com/cart.php?action=add&product_id=264',
        url: 'https://intexcorp.com/products/above-ground-pools/krystal-clear-filtration-sanitation/cartridge-filter-pumps/1000-gph-krystal-clear-cartridge-filter-pump-110-120v-with-gfci/',
    },
    {
      brand: 'intex',
      model: 'intex',
      series: 'intex',
      cartUrl: 'https://intexcorp.com/cart.php?action=add&product_id=1401',
      url: 'https://intexcorp.com/replacement-parts/above-ground-pools/easy-set/15ft-x-42in/2017/28165eh/pump/11469eg-1000-gal-filter-pump-housing-and-motor-120v/',
    },
    {
        brand: 'intex',
        model: 'intex',
        series: 'intex',
        cartUrl: 'https://intexcorp.com/cart.php?action=add&product_id=2571',
        url: 'https://intexcorp.com/products/above-ground-pools/krystal-clear-filtration-sanitation/sand-filter-pumps/1200-gph-krystal-clear-sand-filter-pump-110-120v-with-gfci/',
    },
    {
      brand: 'intex',
      model: 'intex',
      series: 'intex',
      cartUrl: 'https://intexcorp.com/cart.php?action=add&product_id=263',
      url: 'https://intexcorp.com/products/above-ground-pools/krystal-clear-filtration-sanitation/cartridge-filter-pumps/1500-gph-krystal-clear-cartridge-filter-pump-110-120v-with-gfci/',
    },
    {
        brand: 'intex',
        model: 'intex',
        series: 'intex',
        screenshot: 'https://cdn11.bigcommerce.com/s-u7yn5f7nmq/images/stencil/200x200/products/1402/6040/11471EG__97815.1562878683.jpg?c=2',
        cartUrl: 'https://intexcorp.com/cart.php?action=add&product_id=1402',
        url: 'https://intexcorp.com/replacement-parts/above-ground-pools/easy-set/18ft-x-48in/2018/26175eh/pump/11471eg-1500-gal-filter-pump-housing-and-motor-120v/',
    },
    {
        brand: 'intex',
        model: 'intex',
        series: 'intex',
        cartUrl: 'https://intexcorp.com/cart.php?action=add&product_id=2572',
        url: 'https://intexcorp.com/products/above-ground-pools/krystal-clear-filtration-sanitation/sand-filter-pumps/2100-gph-krystal-clear-sand-filter-pump-110-120v-with-gfci/',
    },
    {
      brand: 'intex',
      model: 'intex',
      series: 'intex',
      cartUrl: 'https://intexcorp.com/cart.php?action=add&product_id=94',
      url: 'https://intexcorp.com/products/above-ground-pools/krystal-clear-filtration-sanitation/cartridge-filter-pumps/2500-gph-krystal-clear-cartridge-filter-pump-110-120v-with-gfci/',
    },
    {
      brand: 'intex',
      model: 'intex',
      series: 'intex',
      cartUrl: 'https://intexcorp.com/cart.php?action=add&product_id=2573',
      url: 'https://intexcorp.com/products/above-ground-pools/krystal-clear-filtration-sanitation/sand-filter-pumps/2800-gph-krystal-clear-sand-filter-pump-110-120v-with-gfci/',
    },
    {
        brand: 'intex',
        model: 'intex',
        series: 'intex',
        cartUrl: 'https://intexcorp.com/cart.php?action=add&product_id=3538',
        url: 'https://intexcorp.com/products/above-ground-pools/krystal-clear-filtration-sanitation/combination-systems/krystal-clear-sand-filter-pump-saltwater-system-cg-26675-110-120v-with-gfci/',
    },
    {
        brand: 'intex',
        model: 'intex',
        series: 'intex',
        cartUrl: 'https://intexcorp.com/cart.php?action=add&product_id=3539',
        url: 'https://intexcorp.com/products/above-ground-pools/krystal-clear-filtration-sanitation/combination-systems/krystal-clear-sand-filter-pump-saltwater-system-cg-26679-110-120v-with-gfci/',
    },
    {
      brand: 'intex',
      model: 'intex',
      series: 'intex',
      itemNumber: '2431',
      url: 'https://intexcorp.com/products/above-ground-pools/easy-set/8ft-x-24in-easy-set-pool-set/',
    },
    {
      brand: 'intex',
      model: 'intex',
      series: 'intex',
      url: 'https://intexcorp.com/products/above-ground-pools/easy-set/8ft-x-24in-easy-set-pool/',
    },
    {
        brand: 'intex',
        model: 'intex',
        series: 'intex',
        url: 'https://intexcorp.com/products/above-ground-pools/easy-set/15ft-x-33in-easy-set-pool-set/',
    },
    {
      brand: 'intex',
      model: 'intex',
      series: 'intex',
      url: 'https://intexcorp.com/products/above-ground-pools/easy-set/12ft-x-30in-easy-set-pool-set/',
    },
    {
      brand: 'intex',
      model: 'intex',
      series: 'intex',
      url: 'https://intexcorp.com/products/above-ground-pools/easy-set/10ft-x-30in-easy-set-pool-set/',
    },
    {
      brand: 'intex',
      model: 'intex',
      series: 'intex',
      url: 'https://intexcorp.com/products/above-ground-pools/easy-set/10ft-x-30in-easy-set-pool/',
    },
    {
      brand: 'intex',
      model: 'intex',
      series: 'intex',
      url: 'https://intexcorp.com/products/above-ground-pools/easy-set/8ft-x-30in-easy-set-pool-set/',
    },
    {
      brand: 'intex',
      model: 'intex',
      series: 'intex',
      url: 'https://intexcorp.com/products/above-ground-pools/easy-set/8ft-x-30in-easy-set-pool/',
    }, 
    {
      brand: 'intex',
      model: 'intex',
      series: 'intex',
      url: 'https://intexcorp.com/products/above-ground-pools/easy-set/6ft-x-20in-easy-set-pool/',
    },
    {
      brand: 'intex',
      model: 'intex',
      series: 'intex',
      url: 'https://intexcorp.com/products/above-ground-pools/easy-set/13ft-x-33in-easy-set-pool-set/',
    }, 
    {
      brand: 'intex',
      model: 'intex',
      series: 'intex',
      url: 'https://intexcorp.com/products/above-ground-pools/easy-set/18ft-x-48in-easy-set-pool-set/',
    },
    {
      brand: 'intex',
      model: 'intex',
      series: 'intex',
      url: 'https://intexcorp.com/products/above-ground-pools/easy-set/15ft-x-42in-easy-set-pool-set/',
    }, 
    {
      brand: 'intex',
      model: 'intex',
      series: 'intex',
      url: 'https://intexcorp.com/products/above-ground-pools/easy-set/15ft-x-48in-easy-set-pool-set/',
    }, 
    {
      brand: 'intex',
      model: 'intex',
      series: 'intex',
      url: 'https://intexcorp.com/products/above-ground-pools/metal-frame/8ft-x-20in-metal-frame-pool/',
    },
    {
      brand: 'intex',
      model: 'intex',
      series: 'intex',
      url: 'https://intexcorp.com/products/above-ground-pools/metal-frame/18ft-x-48in-metal-frame-pool-set/',
    }, 
    {
      brand: 'intex',
      model: 'intex',
      series: 'intex',
      url: 'https://intexcorp.com/products/above-ground-pools/metal-frame/15ft-x-48in-metal-frame-pool-set/',
    },
    {
      brand: 'intex',
      model: 'intex',
      series: 'intex',
      url: 'https://intexcorp.com/products/above-ground-pools/metal-frame/10ft-x-30in-metal-frame-pool/',
    },
    {
      brand: 'intex',
      model: 'intex',
      series: 'intex',
      url: 'https://intexcorp.com/products/above-ground-pools/metal-frame/12ft-x-30in-metal-frame-pool/',
    },
    {
      brand: 'intex',
      model: 'intex',
      series: 'intex',
      url: 'https://intexcorp.com/products/above-ground-pools/metal-frame/12ft-x-30in-metal-frame-pool-set/',
    },
    {
      brand: 'intex',
      model: 'intex',
      series: 'intex',
      url: 'https://intexcorp.com/products/above-ground-pools/metal-frame/10ft-x-30in-metal-frame-pool-set/',
    },
    {
      brand: 'intex',
      model: 'intex',
      series: 'intex',
      url: 'https://intexcorp.com/products/above-ground-pools/prism-frame/20ft-x-10ft-x-48in-prism-frame-oval-pool-set/',
    },
    {
      brand: 'intex',
      model: 'intex',
      series: 'intex',
      url: 'https://intexcorp.com/products/above-ground-pools/prism-frame/16ft-6in-x-9ft-x-48in-prism-frame-oval-pool-set/',
    },
    {
      brand: 'intex',
      model: 'intex',
      series: 'intex',
      url: 'https://intexcorp.com/products/above-ground-pools/prism-frame/16ft-x-8ft-x-42in-prism-frame-rectangular-pool-set/',
    },
    {
      brand: 'intex',
      model: 'intex',
      series: 'intex',
      url: 'https://intexcorp.com/products/above-ground-pools/prism-frame/20ft-x-52in-prism-frame-pool-set/',
    },   
    {
      brand: 'intex',
      model: 'intex',
      series: 'intex',
      url: 'https://intexcorp.com/products/above-ground-pools/prism-frame/18ft-x-48in-prism-frame-pool-set/',
    }, 
    {
      brand: 'intex',
      model: 'intex',
      series: 'intex',
      url: 'https://intexcorp.com/products/above-ground-pools/prism-frame/15ft-x-48in-prism-frame-pool-set/',
    }, 
    {
      brand: 'intex',
      model: 'intex',
      series: 'intex',
      url: 'https://intexcorp.com/products/above-ground-pools/prism-frame/15ft-x-42in-prism-frame-pool-set/',
    },    
    {
      brand: 'intex',
      model: 'intex',
      series: 'intex',
      url: 'https://intexcorp.com/products/above-ground-pools/prism-frame/14ft-x-42in-prism-frame-pool-set/',
    },
    {
      brand: 'intex',
      model: 'intex',
      series: 'intex',
      url: 'https://intexcorp.com/products/above-ground-pools/prism-frame/12ft-x-30in-prism-frame-pool-set/',
    }, 
    {
      brand: 'intex',
      model: 'intex',
      series: 'intex',
      url: 'https://intexcorp.com/products/above-ground-pools/prism-frame/12ft-x-30in-prism-frame-pool/',
    }, 
    {
      brand: 'intex',
      model: 'intex',
      series: 'intex',
      url: 'https://intexcorp.com/products/above-ground-pools/prism-frame/10ft-x-30in-prism-frame-pool-set/',
    }, 
    {
      brand: 'intex',
      model: 'intex',
      series: 'intex',
      url: 'https://intexcorp.com/products/above-ground-pools/prism-frame/10ft-x-30in-prism-frame-pool/',
    },
  ],
  name: 'intex',
};
