import {Store} from './store';

export const Pny: Store = {
  currency: '$',
  labels: {
    inStock: {
      container: '#ctl01_lbtnAddToCart',
      text: ['add to cart'],
    },
    maxPrice: {
      container: 'span[itemprop="price"]',
      euroFormat: false,
    },
  },
  links: [
    {
      brand: 'test:brand',
      model: 'test:model',
      series: 'test:series',
      url: 'https://www.pny.com/pny-geforce-gtx-1660-super-gaming-oc-sf',
      loginUrl: 'https://www.pny.com/my-account',
      cartUrl: 'https://www.pny.com/view-cart',
    },
    {
      name: 'PNY GeForce RTX 3060 XLR8 REVEL',
      brand: 'pny',
      model: 'xlr8 revel',
      series: '3060',
      url: 'https://www.pny.com/geforce-rtx-3060-12gb-xlr8-gaming-revel-epic-x-rgb-df',
      loginUrl: 'https://www.pny.com/my-account',
      cartUrl: 'https://www.pny.com/view-cart',
    },
    {
      name: 'PNY GeForce RTX 3060 UPRISING Dual Fan',
      brand: 'pny',
      model: 'uprising',
      series: '3060',
      url: 'https://www.pny.com/geforce-rtx-3060-12gb-uprising-df',
      loginUrl: 'https://www.pny.com/my-account',
      cartUrl: 'https://www.pny.com/view-cart',
    },
    {
      name: 'PNY GeForce RTX 3060 XLR8 REVEL Single Fan',
      brand: 'pny',
      model: 'xlr8 revel',
      series: '3060',
      url:'https://www.pny.com/pny-geforce-rtx-3060-12gb-xlr8-gaming-revel-epic-x-rgb-sf',
      loginUrl: 'https://www.pny.com/my-account',
      cartUrl: 'https://www.pny.com/view-cart',
    },
    {
      name: 'PNY GeForce RTX 3060 Ti UPRISING',
      brand: 'pny',
      model: 'dual fan',
      series: '3060',
      url: 'https://www.pny.com/geforce-rtx-3060-12gb-xlr8-gaming-revel-epic-x-rgb-df',
    },
    {
      name: 'PNY GeForce RTX 3060 Ti REVEL',
      brand: 'pny',
      model: 'single fan',
      series: '3060',
      url: 'https://www.pny.com/pny-geforce-rtx-3060-12gb-xlr8-gaming-revel-epic-x-rgb-sf',
    },
    {
      name: 'PNY GeForce RTX 3070 UPRISING Dual Fan',
      brand: 'pny',
      model: 'dual fan',
      series: '3070',
      url: 'https://www.pny.com/pny-geforce-rtx-3070-8gb-df',
      loginUrl: 'https://www.pny.com/my-account',
      cartUrl: 'https://www.pny.com/view-cart',
    },
    {
      name: 'PNY GeForce RTX 3070 XLR8 Gaming REVEL',
      brand: 'pny',
      model: 'xlr8 revel',
      series: '3070',
      url: 'https://www.pny.com/geforce-rtx-3070-xlr8-gaming-epic-x-rgb-triple-fan',
    },
    {
      name: 'PNY GeForce RTX 3080 XLR8 Gaming UPRISING',
      brand: 'pny',
      model: 'xlr8 uprising',
      series: '3080',
      url: 'https://www.pny.com/geforce-rtx-3080-xlr8-gaming-epic-x-rgb-triple-fan-m',
      loginUrl: 'https://www.pny.com/my-account',
      cartUrl: 'https://www.pny.com/view-cart',
    },
    {
      name: 'PNY GeForce RTX 3080 XLR8 Gaming REVEL',
      brand: 'pny',
      model: 'xlr8 revel',
      series: '3080',
      url: 'https://www.pny.com/geforce-rtx-3080-xlr8-gaming-epic-x-rgb-triple-fan-m',
    },
    {
      name: 'PNY GeForce RTX 3090 XLR8 Gaming UPRISING',
      brand: 'pny',
      model: 'xlr8 revel',
      series: '3080',
      url: 'https://www.pny.com/geforce-rtx-3080-xlr8-gaming-epic-x-rgb-triple-fan-p',
    },
    {
      name: 'PNY GeForce RTX 3090 XLR8 Gaming REVEL',
      brand: 'pny',
      model: 'xlr8 revel',
      series: '3090',
      url: 'https://www.pny.com/geforce-rtx-3090-xlr8-gaming-epic-x-rgb-triple-fan-m',
    },
    {
      brand: 'pny',
      model: 'xlr8 revel',
      series: '3090',
      url: 'https://www.pny.com/geforce-rtx-3090-xlr8-gaming-epic-x-rgb-triple-fan-p',
    },
  ],
  name: 'pny',
};
